### ISSUE TITLE
Where in the code is the function that recurses all the available workbench commands? 

### ISSUE THREAD

**Issue by luzpaz** [triplus/Launcher#5]
Hey triplus, quick question, trying to understand from your code how you access and store all the available commands that get searched and autocomplete as the user types them in to the modal dialog?

**Comment by triplus** [comment]
Each command in FreeCAD, once module gets loaded, gets a corresponding QAction. QActions are therefore what i use in my modules for the mentioned purposes.

**Comment by luzpaz** [comment]
Thanks!
